service:
  name: hello-world
  webpackConfig: webpack.config
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    name: hello
    script: index
    events:
      - http:
          url: example.com/hello
          method: GET
